spring:
  config.activate.on-profile: default
  datasource:
    url: jdbc:mysql://localhost:3306/shop_db
    username: shop
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    # driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  devtools:
    livereload:
      enabled: true
  resources:
    static-locations: file:src/main/resources/static/
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace